### PR TITLE
Experimental build

### PR DESCRIPTION
**Pull request by eps1lon**
Includes:
- https://github.com/merceyz/typescript-to-proptypes/pull/25

### CODE REVIEW

**Comment by merceyz** [comment]
Just a small note, yarn supports installing GitHub dependencies

**Comment by eps1lon** [comment]
> Just a small note, yarn supports installing GitHub dependencies

How does it know how to build the repo? Yarn v1 also?

**Comment by merceyz** [comment]
> How does it know how to build the repo?

v2: Runs `yarn pack` -> `yarn prepack` -> `yarn build`
v1: Runs `yarn prepare`

> Yarn v1 also?

Right, so v1 only runs the `prepare` script, but it performs the install with v1 and not the checked in version (v2) so it doesn't work anyways.

**Comment by eps1lon** [comment]
I need it for the Material-UI repo so if github deps don't work with V1 I need to  use csb. Takes no more than 30s so that's fine by me.

**Pull request closed without merging**
